# Site settings
name: Ronak Mallik
description: "Pretty Swell Dude"
url: "http://rkmallik.com"


# Delete the lines you don't need
# about 5 elements are recomended
twitter_username: ronak
linkedin_username: rkmallik
lastfm_username: bobathia
github_username:  rkmallik
facebook_username: rkmallik
instagram_username:  rkmallik
flickr_username: ronakm
email: ronak@rkmallik.com

avatar: yes
avatar_img_path: "imgs/IMG_20160816_225358.jpg"
# You can link to your GitHub image. That way it will get updated
# automatically whenever you change your GitHub profile picture
#avatar_img_path: "https://avatars2.githubusercontent.com/u/17301305"

front_img: yes
front_img_path: "imgs/bg.jpg"
#front_img_path: "https://external.url/image.jpg"

favicon_img: yes
favicon_img_path: "imgs/favicon.ico"
#favicon_img_path: "https://external.url/favicon.ico"

# Build settings
markdown: kramdown
permalink: pretty
